lib/melo_web/router.ex
defmodule MeloWeb.Router do
  use MeloWeb, :router
  require Ueberauth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {MeloWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/auth", MeloWeb do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
  end

  scope "/", MeloWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/image/:id", PageController, :image
    get "/tag", PageController, :tags
    get "/tag/:slug", PageController, :tag
    get "/random", PageController, :random

    get "/feeds/newest", FeedController, :index
    get "/logout", AuthController, :logout

    get "/admin", AdminController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", MeloWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: MeloWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/melo_web/views/layout_view.ex
defmodule MeloWeb.LayoutView do
  use MeloWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/melo_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= Phoenix.Flash.get(@flash, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= Phoenix.Flash.get(@flash, :error) %></p>
  <%= @inner_content %>
</main>

lib/melo_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert" phx-click="lv:clear-flash" phx-value-key="info">
    <%= live_flash(@flash, :info) %>
  </p>

  <p class="alert alert-danger" role="alert" phx-click="lv:clear-flash" phx-value-key="error">
    <%= live_flash(@flash, :error) %>
  </p>

  <%= @inner_content %>
</main>

lib/melo_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tag() %>
    <%= live_title_tag(assigns[:page_title] || "Pixelvore") %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")} />
    <script
      defer
      phx-track-static
      type="text/javascript"
      src={Routes.static_path(@conn, "/assets/app.js")}
    >
    </script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav>
          <ul>
            <li><%= link("index", to: Routes.page_path(@conn, :index)) %></li>
            <li><%= link("tags", to: Routes.page_path(@conn, :tags)) %></li>
            <li><%= link("random", to: Routes.page_path(@conn, :random)) %></li>
            <%= if @current_user do %>
              <li><%= @current_user.name %></li>
              <li><%= link("admin", to: Routes.admin_path(@conn, :index)) %></li>
              <li class="active"><a href="/logout">logout</a></li>
            <% else %>
              <li><a href="/auth/auth0">login</a></li>
            <% end %>
          </ul>
        </nav>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>